# Generated by Django 3.2.16 on 2022-11-01 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20221031_2302'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Label',
        ),
    ]
